sethal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from accounts.views import ContactView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path('accounts/', include("django.contrib.auth.urls")),
    path("user/", include("user.urls")),
    path("contact/", ContactView, name="contact"),
    path('contact/success/', TemplateView.as_view(template_name='contact_success.html'), name='contact_success'),

    path("", TemplateView.as_view(template_name="index.html"), name="index"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppingcart/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from shoppingcart.views import add_to_cart, view_cart,checkout, remove

app_name = "shoppingcart"

urlpatterns = [
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('view-cart/', view_cart, name='view-cart'),
    path('checkout/', checkout, name='checkout'),
    path('remove/<int:product_id>/', remove, name='remove'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup_view, name='signup'),
    path('verify-email/', views.verify_email, name='verify-email'),
    path('verify-email/done/', views.verify_email_done, name='verify-email-done'),
    path('verify-email-confirm/<uidb64>/<token>/', views.verify_email_confirm, name='verify-email-confirm'),
    path('verify-email/complete/', views.verify_email_complete, name='verify-email-complete'),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/checkout.html
{% extends 'registration/main.html' %}
{% load static %}
{% block content %}
     <div class="row">
		<div class="col-lg-6">
			<div class="box-element" id="form-wrapper">
				<form id="form">
	<div class="login_buttons">
                                  {% csrf_token %}
                                  {% if user.is_authenticated %}
                                  <p>{{ user.email }}!</p>
					{% endif %}
    
    </div>
            <tbody>
                            <tr>
                                <td colspan="3"><strong>Total</strong></td>
                                <td><strong>${{ total_price }}</strong></td>
                            </tr>
                        </tbody>
						<hr>
					<input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue To Checkout">
				</form>
                </form>
			</div>

			<br>
			<div class="box-element hidden" id="payment-info">
				<!--<button id="make-payment">Make payment</button>-->
				<div id="paypal-button-container"></div>
			</div>
			
		</div>

		<div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'shoppingcart:view-cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
            <tbody>
                            <tr>
                                <td colspan="3"><strong>Total</strong></td>
                                <td><strong>${{ total_price }}</strong></td>
                            </tr>
                        </tbody>
            
			</div>
	</div>
    
<script type="application/javascript" src="https://js.stripe.com/v3/"></script>
<script>
    function validateForm(data) {
        let errors = []

        if (data.first_name === '') {
            errors.push('First name is empty')
        }

        if (data.last_name === '') {
            errors.push('Last name is empty')
        }

        if (data.email === '') {
            errors.push('Email is empty')
        }

        if (data.phone === '') {
            errors.push('Phone is empty')
        }

        if (data.address === '') {
            errors.push('Address is empty')
        }

        if (data.zipcode === '') {
            errors.push('Zipcode is empty')
        }

        if (data.place === '') {
            errors.push('Place is empty')
        }

        return errors
    }

    function buy(event) {
        event.preventDefault()

        let data = {
            'first_name': document.querySelector('input[name=first_name]').value,
            'last_name': document.querySelector('input[name=last_name]').value,
            'email': document.querySelector('input[name=email]').value,
            'phone': document.querySelector('input[name=phone]').value,
            'address': document.querySelector('input[name=address]').value,
            'zipcode': document.querySelector('input[name=zipcode]').value,
            'place': document.querySelector('input[name=place]').value,
        }

        let errors = validateForm(data)

        if (errors.length) {
            console.log('Errors', errors)
        } else {
            var stripe = Stripe('{{ pub_key }}')

            fetch('/order/start_order/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                credentials: 'same-origin',
                body: JSON.stringify(data)
            })
            .then(function(response) {
                return response.json()
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.session.id })
            })
            .then(function(result) {
                if (result.error) {
                    alert(result.error.message)
                }
            })
            .catch(function(error) {
                console.log('Errors', error)
            })
        }

        return false
    }
</script>
     </div>
{% endblock %}

templates/client.html
{% extends "registration/base.html" %}
{% load static %}
<!doctype html>
<html lang="en">
  <head>
  	<title>Sethal</title>
	</head>
  <script>
        function redirectToPage() {
            window.location.href = "{% url 'shoppingcart:checkout' %}";
        }
    </script>
	<body>


{% block content %}
  <h2>Add a new address</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" onclick="redirectToPage()">Save</button>

  </form>
{% endblock %}
	</body>
</html>

templates/contact.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>sethal.com</title>
<link href="{%static 'css/bootstrap.css'%}" rel='stylesheet' type='text/css' />
<link href="{%static 'css/style.css'%}" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="{%static 'js/jquery.min.js'%}"></script>
<script type="text/javascript">
        $(document).ready(function() {
            $(".dropdown img.flag").addClass("flagvisibility");

            $(".dropdown dt a").click(function() {
                $(".dropdown dd ul").toggle();
            });
                        
            $(".dropdown dd ul li a").click(function() {
                var text = $(this).html();
                $(".dropdown dt a span").html(text);
                $(".dropdown dd ul").hide();
                $("#result").html("Selected value is: " + getSelectedValue("sample"));
            });
                        
            function getSelectedValue(id) {
                return $("#" + id).find("dt a span.value").html();
            }

            $(document).bind('click', function(e) {
                var $clicked = $(e.target);
                if (! $clicked.parents().hasClass("dropdown"))
                    $(".dropdown dd ul").hide();
            });


            $("#flagSwitcher").click(function() {
                $(".dropdown img.flag").toggleClass("flagvisibility");
            });
        });
     </script>
 </head>
<body>
	<div class="header">
		<div class="container">
			<div class="row">
			  <div class="col-md-12">
				 <div class="header-left">
					 <div class="logo">
						<a href="index.html"><img src="images/logo.png" alt=""/></a>
					 </div>
		<div class="menu">
						    <ul class="nav" id="nav">
                                <li><a href="{% url 'index'%}">Home</a></li>
						    	<li><a href="{% url 'shop'%}">Shop</a></li>
						    	<li><a href="{% url 'about'%}">About Us</a></li>
								<li><a href="{% url 'contact'%}">Contact</a></li>								
								<div class="clear"></div>
							</ul>
							<script type="text/javascript" src="{% static '/js/responsive-nav.js' %}"></script>
				    </div>													
	    		    <div class="clear"></div>
	    	    </div>
	            <div class="header_right">
				    <ul class="icon1 sub-icon1 profile_img">
					 <li><a class="active-icon c1" href="#"> </a>
						<ul class="sub-icon1 list">
						  <div class="product_control_buttons">
						  	<a href="#"><img src="images/edit.png" alt=""/></a>
						  		<a href="#"><img src="images/close_edit.png" alt=""/></a>
						  </div>
						   <div class="clear"></div>
						  <li class="list_img"><img src="images/1.jpg" alt=""/></li>
						  <li class="list_desc"><h4><a href="#"></a></h4><span class="actual"></span></li>
						  <div class="login_buttons">
                                  {% csrf_token %}
                                  {% if user.is_authenticated %}
                                  <p>Hi {{ user.email }}!</p>
							 <p><a href="{% url 'password_change' %}">Password Change</a></p>
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>
{% else %}
                                      <p>You are not logged in</p>
<p><a href="{% url 'password_reset' %}">Password Reset</a></p>
<p><a href="{% url 'login' %}">Log In</a></p>
{% endif %}
							 <div class="clear"></div>
                          <form action="{% url 'signup' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Sign Up</button>
</form>
						  <div class="clear"></div>
                          </div>
                        </ul>
					 </li>
				   </ul>
		        <div class="clear"></div>
	       </div>
	      </div>
		 </div>
	    </div>
	  </div>
     <div class="main">
      <div class="shop_top">
		<div class="container">
			<div class="row">
				<div class="col-md-7">
				</div>
			</div>
            <script src='https://www.google.com/recaptcha/api.js?v=6'></script>
			<div class="row">
				<div class="col-md-12 contact">
				  <form method="post" action="/contact/">
                      {% csrf_token %}
					<div class="to">
                        <input type="text" name="name" placeholder="Your Name" required>
                        <input type="email" name="email" placeholder="Your Email" required>
                        <input type="text" name="subject" placeholder="Subject" required>
                    </div>
                      
					<div class="text">
	                           <textarea name="message" placeholder="Your Message" required></textarea>
                        <button type="submit">Submit</button> 
	</form>
                        
	                </div>
	                <div class="clear"></div>
                   </form>
			     </div>
		    </div>
	     </div>
	   </div>
	  </div>
	  <div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<ul class="footer_box">
							<h4>Newsletter</h4>
							<div class="footer_search">
				    		   <form>
				    			<input type="text" value="Enter your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your email';}">
				    			<input type="submit" value="Go">
				    		   </form>
					        </div>
		   				</ul>
					</div>
				</div>
				<div class="row footer_bottom">
   				</div>
			</div>
		</div>
</body>	
</html>

templates/contact_success.html
{% extends 'registration/base.html' %}
<!DOCTYPE html>
<html>
<head>
    <title>Contact Success</title>
</head>
<body>
    <h1>Thank you for your message!</h1>
    <p>We will get back to you soon.</p>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE HTML>
<html lang="en">
<head>
<title>sethal.com</title>
<link href="{% static "css/bootstrap.css" %}" rel='stylesheet' type='text/css'/>
<link href="{% static "css/style.css" %}" rel='stylesheet' type='text/css'/>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="{% static '/js/jquery.min.js' %}"></script>
<!--<script src="js/jquery.easydropdown.js"></script>-->
<!--start slider -->
<link rel="stylesheet" href="{% static '/css/fwslider.css' %}" media="all"/>
<script src="{% static '/js/jquery-ui.min.js'%}"></script>
<script src="{% static '/js/fwslider.js'%}"></script>
<!--end slider -->
<script type="text/javascript">
        $(document).ready(function() {
            $(".dropdown img.flag").addClass("flagvisibility");

            $(".dropdown dt a").click(function() {
                $(".dropdown dd ul").toggle();
            });
                        
            $(".dropdown dd ul li a").click(function() {
                var text = $(this).html();
                $(".dropdown dt a span").html(text);
                $(".dropdown dd ul").hide();
                $("#result").html("Selected value is: " + getSelectedValue("sample"));
            });
                        
            function getSelectedValue(id) {
                return $("#" + id).find("dt a span.value").html();
            }

            $(document).bind('click', function(e) {
                var $clicked = $(e.target);
                if (! $clicked.parents().hasClass("dropdown"))
                    $(".dropdown dd ul").hide();
            });


            $("#flagSwitcher").click(function() {
                $(".dropdown img.flag").toggleClass("flagvisibility");
            });
        });
     </script>
</head>
<body>

	<div class="header">
		<div class="container">
			<div class="row">
			  <div class="col-md-12">
				 <div class="header-left">
					 <div class="logo">
						<a href="{% url 'index'%}">
                            <img src="{% static '' %}" alt=""/></a>
					 </div>
					 <div class="menu">
						    <ul class="nav" id="nav">
                                <li><a href="{% url 'index'%}">Home</a></li>
						    	<li><a href="{% url 'shop'%}">Shop</a></li>
						    	<li><a href="{% url 'about'%}">About Us</a></li>
								<li><a href="{% url 'contact'%}">Contact</a></li>								
								<div class="clear"></div>
							</ul>
							<script type="text/javascript" src="{% static '/js/responsive-nav.js' %}"></script>
				    </div>							
	    		    <div class="clear"></div>
	    	    </div>
	            <div class="header_right">
	    		  <!-- start search-->
						<!----//search-scripts---->
				    <ul class="icon1 sub-icon1 profile_img">
					 <li><a class="active-icon c1" href="#"> </a>
						<ul class="sub-icon1 list">
						  <div class="product_control_buttons">
						  	<a href="#"><img src="" alt=""/></a>
						  		<a href="#"><img src="" alt=""/></a>
						  </div>
						   <div class="clear"></div>
						  <li class="list_img"><img src="" alt=""/></li>
                        <!----list_desc e eklenecek olan ürünün fiyatı içi kod yerleştir 12 dolar yazıyordu--->
						  <li class="list_desc"><h4><a href="#"></a></h4><span class="actual"></span></li>
						  <div class="login_buttons">
                                  {% csrf_token %}
                                  {% if user.is_authenticated %}
                                  <p>Hi {{ user.email }}!</p>
							 <p><a href="{% url 'password_change' %}">Password Change</a></p>
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>
{% else %}
                                      <p>You are not logged in</p>
<p><a href="{% url 'password_reset' %}">Password Reset</a></p>
<p><a href="{% url 'login' %}">Log In</a></p>
{% endif %}
							 <div class="clear"></div>
                          <form action="{% url 'signup' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Sign Up</button>
</form>
						  </div>
						  <div class="clear"></div>
						</ul>
					 </li>
				   </ul>
		           <div class="clear"></div>
	       </div>
	      </div>
		 </div>
	    </div>
	</div>
	<div class="banner">
	<!-- start slider -->
       <div id="fwslider">
         <div class="slider_container">
            <div class="slide"> 
                <!-- Slide image -->
               <img src="{% static 'images/logo.gif' %}" class="img-responsive" alt=""/>
                <!-- /Slide image -->
                <!-- Texts container -->
                <div class="slide_content">
                    <div class="slide_content_wrap">
                        <!-- Text title -->
                        <h1 class="title"><br></h1>
                        <!-- /Text title -->
                </div>
               <!-- /Texts container -->
            </div>
            <!-- /Duplicate to create more slides -->
            <!--/slide -->
        </div>
        <div class="slidePrev"><span></span></div>
        <div class="slideNext"><span></span></div>
       </div>
       <!--/slider -->
      </div>
	  <div class="main">
		<div class="content-top">
			<h2>something</h2>
			<p></p>
		<h3></h3>
			<script type="text/javascript">
		$(window).load(function() {
			$("#flexiselDemo3").flexisel({
				visibleItems: 5,
				animationSpeed: 1000,
				autoPlay: true,
				autoPlaySpeed: 3000,    		
				pauseOnHover: true,
				enableResponsiveBreakpoints: true,
		    	responsiveBreakpoints: { 
		    		portrait: { 
		    			changePoint:480,
		    			visibleItems: 1
		    		}, 
		    		landscape: { 
		    			changePoint:640,
		    			visibleItems: 2
		    		},
		    		tablet: { 
		    			changePoint:768,
		    			visibleItems: 3
		    		}
		    	}
		    });
		    
		});
		</script>
		<script type="text/javascript" src="{% static "/js/jquery.flexisel.js" %}"></script>
		</div>
	</div>
	<div class="features">
		<div class="container">
			<h3 class="m_3">Features</h3>
			<div class="close_but"><i class="close1"> </i></div>
			  <div class="row">
				<div class="col-md-3 top_box">
                  </div>
                  <h4 class="m_4"><a href="#"></a></h4>
                  <p class="m_5"></p>
                </div>
                   <h4 class="m_4"><a href="#"></a></h4>
                   <p class="m_5"></p>
				</div>
                   <h4 class="m_4"><a href="#"></a></h4>
                   <h4 class="m_4"><a href="#"></a></h4>
                   <p class="m_5"></p>
				</div>
			</div>
		 </div>
	    </div>
		<div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<ul class="footer_box">
							<h4>Newsletter</h4>
							<div class="footer_search">
				    		   <form>
				    			<input type="text" value="Enter your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your email';}">
				    			<input type="submit" value="Go">
				    		   </form>
					        </div>
						</ul>
					</div>
				</div>
			</div>
		</div>
</body>	
</html>

templates/shipping.html
<div class="container">
  <h1>Shipping</h1>
  <p>Please enter your shipping details.</p>
  <hr />
  <div class="form">
    
  <div class="fields fields--2">
    <label class="field">
      <span class="field__label" for="firstname">First name</span>
      <input class="field__input" type="text" id="firstname" value="John" />
    </label>
    <label class="field">
      <span class="field__label" for="lastname">Last name</span>
      <input class="field__input" type="text" id="lastname" value="Doe" />
    </label>
  </div>
  <label class="field">
    <span class="field__label" for="address">Address</span>
    <input class="field__input" type="text" id="address" />
  </label>
  <label class="field">
    <span class="field__label" for="country">Country</span>
    <select class="field__input" id="country">
      <option value=""></option>
      <option value="unitedstates">United States</option>
    </select>
  </label>
  <div class="fields fields--3">
    <label class="field">
      <span class="field__label" for="zipcode">Zip code</span>
      <input class="field__input" type="text" id="zipcode" />
    </label>
    <label class="field">
      <span class="field__label" for="city">City</span>
      <input class="field__input" type="text" id="city" />
    </label>
    <label class="field">
      <span class="field__label" for="state">State</span>
      <select class="field__input" id="state">
        <option value=""></option>
      </select>
    </label>
  </div>
  </div>
  <hr>
  <button class="button">Continue</button>
</div>

templates/shop.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
<title>sethal.com</title>
<link href="{% static 'css/bootstrap.css'%}" rel='stylesheet' type='text/css' />
<link href="{% static 'css/style.css'%}" rel='stylesheet' type='text/css' />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800' rel='stylesheet' type='text/css'>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<script src="{% static 'js/jquery.min.js'%}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".dropdown img.flag").addClass("flagvisibility");

            $(".dropdown dt a").click(function() {
                $(".dropdown dd ul").toggle();
            });

            $(".dropdown dd ul li a").click(function() {
                var text = $(this).html();
                $(".dropdown dt a span").html(text);
                $(".dropdown dd ul").hide();
                $("#result").html("Selected value is: " + getSelectedValue("sample"));
            });

            function getSelectedValue(id) {
                return $("#" + id).find("dt a span.value").html();
            }

            $(document).bind('click', function(e) {
                var $clicked = $(e.target);
                if (!$clicked.parents().hasClass("dropdown"))
                    $(".dropdown dd ul").hide();
            });

            $("#flagSwitcher").click(function() {
                $(".dropdown img.flag").toggleClass("flagvisibility");
            });

            $('.add-to-cart-form').on('submit', function(event) {
                event.preventDefault();
                var form = $(this);
                var url = form.attr('action');
                var quantity = form.find('input[name="quantity"]').val();

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: {
                        'quantity': quantity,
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                    },
                    success: function(response) {
                        $('#cart-quantity').text(response.total_price);
                        $('#cart-total').text(response.total_price.toFixed(2));
                        alert('Product deleted to cart successfully!');
                    },
                    error: function(response) {
                        alert('An error occurred while adding the product to the cart.');
                    }
                });
            });
        });
    </script>
</head>
<body>
	<div class="header">
		<div class="container">
			<div class="row">
			  <div class="col-md-12">
				 <div class="header-left">
					 <div class="logo">
						<a href="index.html"><img src="../accounts/static/images/logo.png" alt=""/></a>
					 </div>
					 <div class="menu">
						  <a class="toggleMenu" href="#"><img src="{% static 'images/nav.png'%}" alt="" /></a>
						    <ul class="nav" id="nav">
                                <li><a href="{% url 'index'%}">Home</a></li>
						    	<li class="current"><a href="{% url 'shop'%}">Shop</a></li>
						    	<li><a href="{% url 'about'%}">About Us</a></li>
								<li><a href="{% url 'contact'%}">Contact</a></li>
								<div class="clear"></div>
							</ul>
							<script type="text/javascript" src="{% static 'js/responsive-nav.js'%}'"></script>
				    </div>
	    		    <div class="clear"></div>
	    	    </div>
	            <div class="header_right">
				    <ul class="icon1 sub-icon1 profile_img">
					 <li><a class="active-icon c1" href="#"> </a>
						<ul class="sub-icon1 list">
						  <div class="product_control_buttons">
						  	<a href="#"><img src="../accounts/static/images/edit.png" alt=""/></a>
						  		<a href="#"><img src="../accounts/static/images/close_edit.png" alt=""/></a>
						  </div>
						   <div class="clear"></div>
						  <li class="list_img"><img src="../accounts/static/images/1.jpg" alt=""/></li>
                            <li class="list_desc"><h4><a href="#"></a></h4><span class="actual"></span></li>
						  						  <div class="login_buttons">
                                  {% csrf_token %}
                                  {% if user.is_authenticated %}
<p>Hi {{ user.email }}! You have <span id="cart-quantity">{{ user.cartitem_set.count }}</span> item(s) in your cart.</p>
                                        <p>Total amount: $<span id="cart-total">{{ request.user.cartitem_set.aggregate }}</span></p>
                                      <a href="{% url 'shoppingcart:view-cart' %}">View Cart</a>
							 <p><a href="{% url 'password_change' %}">Password Change</a></p>
<form action="{% url 'logout' %}" method="post">
  {% csrf_token %}
  <button type="submit">Log Out</button>
</form>
{% else %}
                                      <p>You are not logged in</p>
<p><a href="{% url 'password_reset' %}">Password Reset</a></p>
<p><a href="{% url 'login' %}">Log In</a></p>
{% endif %}
							 <div class="clear"></div>
                          <form action="{% url 'signup' %}" method="post">
  {% csrf_token %}
  {{ form }}
  <button type="submit">Sign Up</button>
</form>
						  </div>
						  <div class="clear"></div>
						</ul>
					 </li>
				   </ul>
		        <div class="clear"></div>
	       </div>
	      </div>
		 </div>
	    </div>
	  </div>
     <div class="main">
      <div class="shop_top">
		<div class="container">
			<div class="row shop_box-top">
			</div>
			<div class="row">
				{% for product in products %}

				<div class="col-md-3 shop_box"><a href="single.html">
					<span class="new-box">
						<span class="new-label">New</span>
					</span>
					<div class="shop_desc">
						<h3><a href="#">{{product.name}}</a></h3>
						<span class="actual">${{product.price}}</span><br>
						<span class="actual">{{product.description}}</span><br>
                        {% if product.image %}
                         <img src="{{ product.image.url }}" width="200" height="120" alt="{{ product.name }}"/>
                        {% else %}
            <p>No image available</p>
        {% endif %}
                        <form class="add-to-cart-form" action="{% url 'shoppingcart:add_to_cart' product.id %}" method="post">
        {% csrf_token %}
                            <input type="hidden" name="quantity" value="1">
                                <ul class="buttons">
                                    <li class="submitting"><button type="submit">Add To Cart</button></li>
							<div class="clear"> </div>
					    </ul>
    </form>
                       <form class="add-to-cart-form" action="{% url 'shoppingcart:remove' product.id %}" method="post">
        {% csrf_token %}
                            <input type="hidden" name="quantity" value="1">
                                <ul class="buttons">
                                    <li class="submitting"><button type="submit">Remove</button></li>
							<div class="clear"> </div>
					    </ul>
    </form>
				    </div>
				</a>
				</div>
				{% endfor %}
			</div>

		 </div>
	   </div>
	  </div>
	  <div class="footer">
			<div class="container">
				<div class="row">
					<div class="col-md-3">
						<ul class="footer_box">
							<h4>Newsletter</h4>
							<div class="footer_search">
				    		   <form>
				    			<input type="text" value="Enter your email" onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Enter your email';}">
				    			<input type="submit" value="Go">
				    		   </form>
					        </div>

						</ul>
					</div>
				</div>
			</div>
		</div>
</body>
</html>